apiVersion: v1
kind: Pod
metadata:
  name: reader-pod
spec:
  containers:
  - name: reader
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - "sleep 5; ls /data/*.txt || echo 'No .txt files found'"
    volumeMounts:
    - mountPath: /data
      name: shared-storage
  volumes:
  - name: shared-storage
    persistentVolumeClaim:
      claimName: shared-pvc
